# pado_visualize config
# =====================
#
# todo: we should ship the defaults in the module
#
[default]
SERVER = "127.0.0.1"
PORT = 8000

# celery workers
broker_url = "redis://localhost:6379/0"
broker_connection_max_retry = 3  # note: https://github.com/celery/celery/issues/4556
result_backend = "redis://localhost:6379/1"

# flask-caching
CACHE_PATH = "/tmp/pado_visualize_cache"
CACHE_TYPE = "SimpleCache"
CACHE_DEFAULT_TIMEOUT = 300

# no auth. tyvm.
OAUTH_PROVIDER = "none"

# the datasets
DATASET_PATHS = []


[development]
DEBUG = true

[production]
DEBUG = false

# todo: uwsgi config should live in its own file
UWSGI_NUM_PROCESSES = 6
