#
# Conda devenv environment for pavo.
#
# Create the environment, do not install pavo in development mode:
#   conda devenv
# equivalent to:
#   PAVO_DEVEL="" conda devenv
# Create the environment, install pado in development mode:
#   PAVO_DEVEL=TRUE conda devenv
#

# {% set PAVO_DEVEL = os.environ.get('PAVO_DEVEL', False) %}

name: pavo

channels:
  - conda-forge

dependencies:
  - python=3.9  # let's not carry the 3.6, 3.7, 3.8 baggage for now
  - pip
  - importlib_resources
  - typing_extensions

  # dev related
  - nodejs=16.*  # revisit when upgrading js deps
  - pre-commit
  - black
  - pytest
  - pytest-cov
  - mypy

  # webapp related
  - celery
  - click
  - dynaconf
  - filelock
  - flask-caching>=1.8.0
  - flask>=2
  - itsdangerous
  - redis-py
  - werkzeug
  - gunicorn

  # data deps
  - pandas
  - geopandas

  # tiffslide deps
  - fsspec
  - pillow

  # pado deps
  - orjson

  # utils
  - tqdm
  - s3fs
  - typer


  # homemade dependencies on conda
  - tiffslide>=2
  - pado>=0.12

  - pip:
    # homemade dependencies
    - "-e ."  # [ PAVO_DEVEL ]
