#
# Conda devenv environment for pavo.
#
# Create the environment, do not install pavo in development mode:
#   conda devenv
# equivalent to:
#   PAVO_DEVEL="" conda devenv
# Create the environment, install pado in development mode:
#   PAVO_DEVEL=TRUE conda devenv
#

# {% set PAVO_DEVEL = os.environ.get('PAVO_DEVEL', False) %}

name: pavo

channels:
  - conda-forge

dependencies:
  - python=3.9  # let's not carry the 3.6, 3.7, 3.8 baggage for now
  - pip

  # dev related
  - nodejs=16.*  # revisit when upgrading js deps
  - pre-commit
  - pytest
  - pytest-cov
  - mypy
  - supervisor

  # webapp related
  - celery
  - click
  - diskcache
  - dynaconf
  - filelock
  - flask>=2
  - flask-caching>=1.8.0
  - flask-dance
  - flower
  - redis-py
  - werkzeug
  - pyopenssl

  # data deps
  - numpy
  - pandas
  - rasterio

  # tiffslide deps
  - fsspec
  - imagecodecs
  - pillow
  - tifffile>=2020.10.1
  - zarr

  # pado deps
  - platformdirs
  - orjson
  - toml
  - pyarrow
  - shapely
  - pydantic
  - geojson-pydantic

  # utils
  - tqdm
  - s3fs
  - typer

  - geopandas
  - gettext
  - gunicorn

  # homemade dependencies on conda
  - tiffslide>=2
  - pado>=0.12

  - pip:
    # homemade dependencies
    - "-e ."  # [ PAVO_DEVEL ]
