#
# Conda devenv environment for palo.
# Beware, this fat environment might get you in trouble, treat with care.
#
# Create the environment, do not install pado in development mode:
#   conda devenv
# equivalent to:
#   PADO_VISUALIZE_DEVEL="" conda devenv
# Create the environment, install pado in development mode:
#   PADO_VISUALIZE_DEVEL=TRUE conda devenv
#

{% set PADO_VISUALIZE_DEVEL = os.environ.get('PADO_VISUALIZE_DEVEL', False) %}

name: pado_visualize

channels:
  - sdvillal
  - pytorch
  - conda-forge

dependencies:
  - python
  - pip

  - diskcache
  - dynaconf
  - flask-caching
  - flask-dance
  - werkzeug
  - pyopenssl

  - numpy
  - pandas
  - tifffile>=2020.10.1
  - pillow
  - rasterio

  - tqdm

  - pip:
    - git+ssh://git@github.com/bayer-science-for-a-better-life/pado.git#egg=pado
    - Flask-JSGlue
    - tiffslide
    - simplejpeg
    # old deps need to get rid of them

    - dash
    - dash-auth
    - dash-bootstrap-components
    - dash-table
    - plotly

    - "-e ."  # [ PADO_VISUALIZE_DEVEL ]
