name: "MLR Memorable Milestones"
on:
  schedule:
  - cron: "*/30 * * * *"

jobs:
  memorable-milestones:
    runs-on: ubuntu-latest
    steps:
    - uses: bayer-int/mlr-automated-milestones@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
